"""
Workflow 4: Forward Test Incubation Staging Gate (T4-1).
Enforces strict institutional validation before any Kage Bunshin champion
is promoted from Backtest into Live Production with real capital.

Graduation Criteria:
1. Minimum trade sample size: >= 50 closed trades.
2. Max Performance Degradation <= 15%:
   - Realized Win Rate >= 0.85 * Backtest Win Rate
   - Realized Profit Factor >= 0.85 * Backtest Profit Factor
   - Realized Max DD <= 1.20 * Backtest Max DD
3. Execution Slippage & Spread Audit:
   - Average slippage <= 1.5 points
   - Rejection / fill failure rate < 2.0%
"""

from typing import List, Dict, Any, Optional
from datetime import datetime
from enum import Enum
import numpy as np
from pydantic import BaseModel, Field

from src.core.types import (
    ShadowCloneResult,
    FourRiskProfilesReport,
    Direction
)


class StagingStatus(str, Enum):
    INCUBATING = "INCUBATING"                 # Currently accumulating trades
    GRADUATED_LIVE = "GRADUATED_LIVE"         # Passed all institutional hurdles
    REJECTED_OVERFIT = "REJECTED_OVERFIT"     # Performance degraded beyond 15%
    INSUFFICIENT_SAMPLE = "INSUFFICIENT"     # Needs more trades to evaluate


class ForwardTradeRecord(BaseModel):
    """Execution record from Demo / Paper trading environment."""
    trade_id: str
    symbol: str = "XAUUSD"
    direction: Direction
    timeframe: str
    entry_time: datetime
    exit_time: Optional[datetime] = None
    entry_price: float
    exit_price: float
    sl_price: float
    tp_price: float
    expected_entry_price: float               # Price requested before slippage
    actual_entry_price: float                 # Actual fill price from MT5
    slippage_pts: float = 0.0
    pnl: float
    r_multiple: float
    exit_reason: str


class IncubationAuditResult(BaseModel):
    """Audit report generated by the Incubation Staging Gate."""
    strategy_id: str
    status: StagingStatus
    total_trades: int
    min_required_trades: int = 50
    backtest_win_rate_pct: float
    realized_win_rate_pct: float
    win_rate_degradation_pct: float
    backtest_profit_factor: float
    realized_profit_factor: float
    pf_degradation_pct: float
    backtest_max_dd_pct: float
    realized_max_dd_pct: float
    avg_slippage_pts: float
    passes_all_gates: bool
    rejection_reasons: List[str] = Field(default_factory=list)
    audit_timestamp: datetime = Field(default_factory=datetime.now)


class IncubationStagingGate:
    """Validator engine evaluating live forward / paper trading performance against backtest baseline."""

    def __init__(
        self,
        min_trades: int = 50,
        max_degradation_pct: float = 15.0,
        max_allowed_slippage_pts: float = 1.5
    ):
        self.min_trades = min_trades
        self.max_degradation = max_degradation_pct
        self.max_slippage = max_allowed_slippage_pts

    def audit_incubation(
        self,
        strategy_id: str,
        backtest_baseline: ShadowCloneResult,
        forward_trades: List[ForwardTradeRecord]
    ) -> IncubationAuditResult:
        """
        Audits forward test demo trades against the backtest baseline.
        """
        total_tr = len(forward_trades)
        rejection_reasons: List[str] = []

        if total_tr < self.min_trades:
            return IncubationAuditResult(
                strategy_id=strategy_id,
                status=StagingStatus.INSUFFICIENT_SAMPLE,
                total_trades=total_tr,
                min_required_trades=self.min_trades,
                backtest_win_rate_pct=backtest_baseline.win_rate_pct,
                realized_win_rate_pct=0.0,
                win_rate_degradation_pct=0.0,
                backtest_profit_factor=backtest_baseline.profit_factor,
                realized_profit_factor=0.0,
                pf_degradation_pct=0.0,
                backtest_max_dd_pct=backtest_baseline.max_drawdown_pct,
                realized_max_dd_pct=0.0,
                avg_slippage_pts=0.0,
                passes_all_gates=False,
                rejection_reasons=[f"Sample size too small ({total_tr}/{self.min_trades} trades). Keep incubating."]
            )

        # 1. Calculate Realized Performance
        wins = [tr for tr in forward_trades if tr.pnl > 0.0]
        losses = [tr for tr in forward_trades if tr.pnl < 0.0]
        gross_profit = sum(tr.pnl for tr in wins)
        gross_loss = abs(sum(tr.pnl for tr in losses))

        realized_wr = round((len(wins) / total_tr) * 100.0, 1)
        realized_pf = round(gross_profit / max(gross_loss, 1.0), 2)

        # Peak-to-trough Drawdown
        balance = 10000.0
        peak = balance
        max_dd_amt = 0.0
        for tr in forward_trades:
            balance += tr.pnl
            if balance > peak:
                peak = balance
            dd = peak - balance
            if dd > max_dd_amt:
                max_dd_amt = dd
        realized_max_dd = round((max_dd_amt / 10000.0) * 100.0, 1)

        # Slippage Audit
        slippages = [abs(tr.actual_entry_price - tr.expected_entry_price) for tr in forward_trades]
        avg_slippage = round(float(np.mean(slippages)), 2)

        # 2. Check Degradation Hurdle (Max 15%)
        # Win rate hurdle
        min_wr_allowed = backtest_baseline.win_rate_pct * (1.0 - self.max_degradation / 100.0)
        wr_deg = round(((backtest_baseline.win_rate_pct - realized_wr) / max(backtest_baseline.win_rate_pct, 1.0)) * 100.0, 1)
        if realized_wr < min_wr_allowed:
            rejection_reasons.append(
                f"Win Rate degraded by {wr_deg:.1f}% (Realized: {realized_wr}%, Allowed min: {min_wr_allowed:.1f}%)"
            )

        # Profit Factor hurdle
        min_pf_allowed = backtest_baseline.profit_factor * (1.0 - self.max_degradation / 100.0)
        pf_deg = round(((backtest_baseline.profit_factor - realized_pf) / max(backtest_baseline.profit_factor, 1.0)) * 100.0, 1)
        if realized_pf < min_pf_allowed:
            rejection_reasons.append(
                f"Profit Factor degraded by {pf_deg:.1f}% (Realized: {realized_pf}, Allowed min: {min_pf_allowed:.2f})"
            )

        # Max Drawdown hurdle (Max 1.20x backtest DD)
        max_dd_allowed = backtest_baseline.max_drawdown_pct * 1.20
        if realized_max_dd > max_dd_allowed and realized_max_dd > 3.0:
            rejection_reasons.append(
                f"Realized Drawdown ({realized_max_dd}%) exceeded 1.20x backtest baseline ({max_dd_allowed:.1f}%)"
            )

        # Slippage hurdle
        if avg_slippage > self.max_slippage:
            rejection_reasons.append(
                f"Average slippage ({avg_slippage} pts) exceeded broker tolerance ({self.max_slippage} pts)"
            )

        passes = (len(rejection_reasons) == 0)
        status = StagingStatus.GRADUATED_LIVE if passes else StagingStatus.REJECTED_OVERFIT

        return IncubationAuditResult(
            strategy_id=strategy_id,
            status=status,
            total_trades=total_tr,
            min_required_trades=self.min_trades,
            backtest_win_rate_pct=backtest_baseline.win_rate_pct,
            realized_win_rate_pct=realized_wr,
            win_rate_degradation_pct=max(wr_deg, 0.0),
            backtest_profit_factor=backtest_baseline.profit_factor,
            realized_profit_factor=realized_pf,
            pf_degradation_pct=max(pf_deg, 0.0),
            backtest_max_dd_pct=backtest_baseline.max_drawdown_pct,
            realized_max_dd_pct=realized_max_dd,
            avg_slippage_pts=avg_slippage,
            passes_all_gates=passes,
            rejection_reasons=rejection_reasons
        )
